package com.ubl.bean;
// Generated Dec 15, 2016 11:00:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dosen generated by hbm2java
 */
public class Dosen  implements java.io.Serializable {


     private String iddosen;
     private String namadosen;
     private Set matakuliahs = new HashSet(0);

    public Dosen() {
    }

	
    public Dosen(String iddosen, String namadosen) {
        this.iddosen = iddosen;
        this.namadosen = namadosen;
    }
    public Dosen(String iddosen, String namadosen, Set matakuliahs) {
       this.iddosen = iddosen;
       this.namadosen = namadosen;
       this.matakuliahs = matakuliahs;
    }
   
    public String getIddosen() {
        return this.iddosen;
    }
    
    public void setIddosen(String iddosen) {
        this.iddosen = iddosen;
    }
    public String getNamadosen() {
        return this.namadosen;
    }
    
    public void setNamadosen(String namadosen) {
        this.namadosen = namadosen;
    }
    public Set getMatakuliahs() {
        return this.matakuliahs;
    }
    
    public void setMatakuliahs(Set matakuliahs) {
        this.matakuliahs = matakuliahs;
    }




}


