package com.ubl.bean;
// Generated Dec 15, 2016 11:00:22 AM by Hibernate Tools 4.3.1



/**
 * Matakuliah generated by hbm2java
 */
public class Matakuliah  implements java.io.Serializable {


     private String kodematakuliah;
     private Dosen dosen;
     private String namamatakuliah;

    public Matakuliah() {
    }

	
    public Matakuliah(String kodematakuliah, Dosen dosen) {
        this.kodematakuliah = kodematakuliah;
        this.dosen = dosen;
    }
    public Matakuliah(String kodematakuliah, Dosen dosen, String namamatakuliah) {
       this.kodematakuliah = kodematakuliah;
       this.dosen = dosen;
       this.namamatakuliah = namamatakuliah;
    }
   
    public String getKodematakuliah() {
        return this.kodematakuliah;
    }
    
    public void setKodematakuliah(String kodematakuliah) {
        this.kodematakuliah = kodematakuliah;
    }
    public Dosen getDosen() {
        return this.dosen;
    }
    
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }
    public String getNamamatakuliah() {
        return this.namamatakuliah;
    }
    
    public void setNamamatakuliah(String namamatakuliah) {
        this.namamatakuliah = namamatakuliah;
    }




}


